apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-example-ingress
  namespace: angular-example
spec:
  rules:
    - host: my-angular.com
      http:
        paths:
          - backend:
              serviceName: angular-example-service
              servicePort: 80
