apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-example-deployment
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-example
  template:
    metadata:
      labels:
        app: angular-example
    spec:
      containers:
      - name: angular-example-container
        image: praveenkumarreddy8498/angular-example:tagname
        ports:
        - containerPort: 80
