apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.5-alpine
        env:
        - name: POSTGRES_DB
          value: bitnami_keycloak
        - name: POSTGRES_USER
          value: bn_keycloak
        - name: POSTGRES_PASSWORD
          value: "#3]O?4RGj)DE7Z!9SA5"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - "-d"
            - "${POSTGRES_DB}"
            - "-U"
            - "${POSTGRES_USER}"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
